env:
  browser: true
extends:
  - plugin:react/recommended
  - google
overrides: []
parserOptions:
  requireConfigFile: false
  ecmaVersion: 8
  sourceType: module
plugins:
  - react
parser: "@babel/eslint-parser"
rules: {
  "no-unused-vars" : "off",
  "react/prop-types": "off",
  "require-jsdoc" : "off",
  "max-len" : "off",
  "no-invalid-this": "off",
  "new-cap" : "off"
}
