env:
  browser: true
extends:
  - plugin:react/recommended
  - google
overrides: []
parserOptions:
  ecmaVersion: 8
  sourceType: module
  parser: '@typescript-eslint/parser'
plugins:
  - react
rules: {
  "no-unused-vars" : "off",
  "react/prop-types" : "off",
  "require-jsdoc" : "off"
}
