name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - working-directory: ./frontend
        run: npm install
      - working-directory: ./backend_node
        run: npm install
      - working-directory: ./backend_node
        run: ./node_modules/.bin/eslint . --fix
      - working-directory: ./backend_node
        run: ./node_modules/.bin/prettier . --write
